export type MintFeedChain = "robinhood" | "ethereum";

export type MintFeedRow = {
  id: string;
  chain: MintFeedChain;
  contract: string;
  name: string;
  image: string;
  slug: string;
  minted: string;
  max: string;
  floor: string;
  mintCount: string;
  mintCountNum: number;
  minters: string;
  volume: string;
  volumeNum: number;
  qty: string;
  tokenId: string;
  minter: string;
  ago: string;
  atMs: number;
  price: string;
  hot: boolean;
  proxy: boolean;
  free: boolean;
  standard: string;
  sales: string;
  change: string;
  changeNum: number;
  rank: string;
};
