const openings = [
  "I'm so f***ing tired of",
  "Can we talk about how tired I am of",
  "Another day, another reason to be tired of",
  "My therapist can't help with how tired I am of",
  "Not to be dramatic but I'm EXHAUSTED by",
  "Dear Web3, I'm tired of",
];

const subjects = [
  "influencers shilling rugs at 3am",
  "Discord mods with 'alpha' that's just recycled Twitter takes",
  "'Community takeovers' that are just new scammers",
  "projects with 47 utility tokens and 0 utility",
  "'Wen marketing' posts from teams that never marketed",
  "fake volume bots making everything look alive",
  "KOLs who 'aped' but actually got paid",
  "whitepapers longer than my will to live",
  "NFT projects pivoting to AI pivoting to memecoins",
  "people saying 'we're so back' every 4 hours",
  "Telegram groups with 50k bots and 3 humans",
  "'Trust the process' when the process is embezzlement",
  "founders who 'got hacked' right after selling",
  "airdrop farmers farming my last shred of hope",
  "chains launching chains launching chains",
];

const closings = [
  "That's why $TIRED exists. We're all exhausted here.",
  "I'm not asking for much. Just honesty and a nap.",
  "At this point I'd rather be tired on Mars than awake on Earth.",
  "The only thing pumping is my blood pressure.",
  "Web3 promised freedom. I got insomnia and bags.",
  "If you're tired too, you're already one of us.",
  "This isn't financial advice. It's emotional damage.",
  "I didn't choose the tired life. The tired life chose me.",
];

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateRant(): string {
  return `${pick(openings)} ${pick(subjects)}.\n\n${pick(closings)}`;
}

export const MANIFESTO_LINES = [
  "We didn't come to Web3 for this.",
  "We came for decentralization.",
  "We got centralization of scams.",
  "",
  "We came for financial freedom.",
  "We got financially ruined.",
  "",
  "We came for the future.",
  "We got airdrop farming and influencer grifts.",
  "",
  "Every cycle the same script:",
  "New chain. New narrative. New rug.",
  "Same tired faces pretending it's different.",
  "",
  "The influencers aren't your friends.",
  "The 'doxxed dev' will delete his LinkedIn.",
  "The 'locked liquidity' unlocks at 3am.",
  "The 'community vote' was rigged by 4 wallets.",
  "",
  "They said HODL.",
  "We held.",
  "They sold.",
  "We're still holding trauma.",
  "",
  "They said WAGMI.",
  "We didn't.",
  "They did.",
  "On our liquidity.",
  "",
  "Diamond hands? Nah.",
  "Depleted uranium hands.",
  "Hands that have seen too much.",
  "Hands that typed 'gm' at 6am for 400 days straight.",
  "",
  "We're not bullish.",
  "We're not bearish.",
  "We're just... tired.",
  "",
  "Tired of the lies.",
  "Tired of the pumps.",
  "Tired of the dumps.",
  "Tired of pretending this is fun.",
  "",
  "$TIRED isn't a moon mission.",
  "It's a support group with a ticker symbol.",
  "",
  "If you've been rugged, dumped on, shilled to, and gaslit by CT —",
  "welcome home.",
  "",
  "We're not going to Mars.",
  "We're going to bed.",
  "",
  "But if we do go to Mars,",
  "it's because Earth ran out of rugs to pull.",
  "",
  "Stay tired. Stay real. Stay $TIRED.",
] as const;
